"""dbt sources.yml -> Dataform sources.js declarations.

Each dbt ``{{ source('src', 'table') }}`` call in a model is rewritten by
``sql_to_sqlx.convert()`` to ``${ref("table")}`` using the table's dbt
``name:``. This module generates the matching ``declare()`` calls so those
refs resolve, using that same ``name:`` -- so the two stay in sync as long
as the source table has no ``identifier:`` override (see the warning below
for when it does).

dbt source.yml:
    sources:
      - name: ecom
        schema: raw
        tables:
          - name: raw_customers

Dataform sources.js:
    declare({
      schema: "raw",
      name: "raw_customers",
    });

Out of MVP scope: freshness checks (no direct Dataform equivalent) and
column-level documentation -- both are flagged for manual review rather
than silently dropped.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ..warnings import ConversionWarning


@dataclass
class SourcesConversionResult:
    js: str
    declared: list[str] = field(default_factory=list)
    warnings: list[ConversionWarning] = field(default_factory=list)


def convert(sources: list[dict[str, Any]]) -> SourcesConversionResult:
    """``sources`` is the list found under the top-level ``sources:`` key
    of one or more dbt sources.yml files, already YAML-parsed."""
    warnings: list[ConversionWarning] = []
    declared: list[str] = []
    blocks: list[str] = []

    for source in sources:
        source_name = source.get("name", "")
        default_schema = source.get("schema", source_name)
        default_database = source.get("database")

        for table in source.get("tables") or []:
            table_name = table.get("name")
            if not table_name:
                continue

            identifier = table.get("identifier")
            physical_name = identifier or table_name
            if identifier and identifier != table_name:
                warnings.append(
                    ConversionWarning(
                        message=(
                            f"source('{source_name}', '{table_name}') has identifier: "
                            f"'{identifier}' in dbt, so the physical table name differs "
                            f'from the source name. Declared as "{physical_name}" here -- '
                            f'update any ${{ref("{table_name}")}} generated from source() '
                            f'calls to ${{ref("{physical_name}")}}.'
                        ),
                    )
                )

            if table.get("freshness") or source.get("freshness"):
                warnings.append(
                    ConversionWarning(
                        message=(
                            f"Freshness check on '{source_name}.{table_name}' was not converted; "
                            f"Dataform has no direct equivalent -- recreate it with a custom "
                            f"assertion or scheduled check if you rely on it."
                        ),
                    )
                )

            blocks.append(
                _render_declare(
                    database=table.get("database", default_database),
                    schema=table.get("schema", default_schema),
                    name=physical_name,
                    description=table.get("description"),
                )
            )
            declared.append(physical_name)

    header = (
        "// Generated by dbt-to-dataform-cli from sources.yml.\n"
        "// Verify database/schema names and any identifier overrides flagged in MIGRATION_REPORT.md.\n\n"
    )
    js = header + "\n\n".join(blocks) + ("\n" if blocks else "")
    return SourcesConversionResult(js=js, declared=declared, warnings=warnings)


def _render_declare(*, database: str | None, schema: str, name: str, description: str | None) -> str:
    lines = ["declare({"]
    if database:
        lines.append(f'  database: "{database}",')
    lines.append(f'  schema: "{schema}",')
    lines.append(f'  name: "{name}",')
    if description:
        escaped = description.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
        lines.append(f'  description: "{escaped}",')
    lines.append("});")
    return "\n".join(lines)
